---
name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build de l'image Docker
        run: docker build -t devsecops-node .

      - name: Lint du Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Installer yamllint
        run: sudo apt-get install -y yamllint

      - name: Lint des fichiers YAML
        run: yamllint .