---
name: Deploy App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build de l'image Docker
        run: docker build -t devsecops-node .

      - name: Lint du Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile

      - name: Installer yamllint
        run: sudo apt-get install -y yamllint

      - name: Lint des fichiers YAML
        run: yamllint .

      - name: Installer Trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release -y
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y

      - name: Scan des dépendances Node.js (package.json)
        run: trivy fs --scanners vuln --severity HIGH,CRITICAL .

      - name: Scan de l’image Docker
        run: |
          docker build -t devsecops-node .
          trivy image --severity HIGH,CRITICAL devsecops-node
