---
name: Deploy App

on:
  push:
    branches:
      - test
      - main
  pull_request:
    branches:
      - test
  workflow_dispatch:
    inputs:
      target:
        description: "Which environment to deploy (test or prod)"
        required: false
        default: "prod"

jobs:
  build_and_deploy_test:
    name: Build & Deploy to Test
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/test'

    environment: testing

    env:
      # Per-environment values should be stored in GitHub Secrets
      PROJECT_ID: ${{ secrets.GCP_PROJECT_TEST }}
      GAR_LOCATION: ${{ secrets.GAR_LOCATION }}
      REPOSITORY_NAME: ${{ secrets.GAR_REPOSITORY_NAME }}
      IMAGE_NAME: ${{ secrets.GAR_IMAGE_NAME }}
      SERVICE_NAME: ${{ secrets.CLOUD_RUN_SERVICE_TEST }}

    permissions:
      contents: read
      id-token: write

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Google auth (Workload Identity)"
        id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT_TEST }}

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: "${{ env.PROJECT_ID }}"

      - name: "Docker auth"
        run: |-
          gcloud auth configure-docker ${{ env.GAR_LOCATION }}-docker.pkg.dev --quiet
      - name: "Build and push Docker image"
        run: |-
          IMAGE_PATH="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE_PATH" .
          docker push "$IMAGE_PATH"
      - name: Deploy to Cloud Run
        run: |
          IMAGE_PATH="${{ env.GAR_LOCATION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          gcloud run services update ajustement-auto-service \
          --image "$IMAGE_PATH" \
          --region europe-west9 \
          --platform managed \
          --quiet
          echo "Deployed to Cloud Run successfully."
