---
name: Deploy App

on:
  push:
    branches:
      - test
  pull_request:
    branches:
      - test

env:
  GCP_REGION: ${{ vars.GCP_REGION }}
  REPOSITORY_NAME: ajustement-auto-repo
  IMAGE_NAME: ajustement-auto

jobs:
  build_and_deploy_test:
    name: Build & Deploy to Test
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && github.ref == 'refs/heads/test'

    environment: Test

    env:
      PROJECT_ID: ${{ vars.PROJECT_ID }}
      SERVICE_ACCOUNT: ${{ vars.SERVICE_ACCOUNT }}
      GCP_WIF_PROVIDER: ${{ vars.GCP_WIF_PROVIDER }}
      GCP_REGION: ${{ vars.GCP_REGION }}
      REPOSITORY_NAME: ajustement-auto-repo
      IMAGE_NAME: ajustement-auto

    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ env.GCP_WIF_PROVIDER }}
          service_account: ${{ env.SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: |
          echo "gcloud auth list"
          gcloud auth list
          echo "Configure Docker"
          gcloud auth configure-docker "${{ env.GCP_REGION }}-docker.pkg.dev" --quiet

      - name: Build and push Docker image
        run: |
          IMAGE_PATH="${{ env.GCP_REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPOSITORY_NAME }}/${{ env.IMAGE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE_PATH" .
          docker push "$IMAGE_PATH"
